################################################################################
# Automatically-generated file. Do not edit!
################################################################################

CPP_SRCS := 
C_SRCS := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
jni/libpng \
jni/SMW \
jni/SDL_net \
jni/SDL_mixer \
jni/SDL_mixer/timidity \
jni/SDL_mixer/native_midi_gpl \
jni/SDL_mixer/native_midi \
jni/SDL_image \
jni/SDL/src/video/x11 \
jni/SDL/src/video/windows \
jni/SDL/src/video/uikit \
jni/SDL/src/video/pandora \
jni/SDL/src/video/nds \
jni/SDL/src/video/dummy \
jni/SDL/src/video/directfb \
jni/SDL/src/video/android \
jni/SDL/src/video \
jni/SDL/src/timer/windows \
jni/SDL/src/timer/wince \
jni/SDL/src/timer/unix \
jni/SDL/src/timer/nds \
jni/SDL/src/timer/dummy \
jni/SDL/src/timer/beos \
jni/SDL/src/timer \
jni/SDL/src/thread/windows \
jni/SDL/src/thread/pthread \
jni/SDL/src/thread/nds \
jni/SDL/src/thread/irix \
jni/SDL/src/thread/generic \
jni/SDL/src/thread/beos \
jni/SDL/src/thread \
jni/SDL/src/stdlib \
jni/SDL/src/render/software \
jni/SDL/src/render/opengles2 \
jni/SDL/src/render/opengles \
jni/SDL/src/render/opengl \
jni/SDL/src/render/nds \
jni/SDL/src/render/direct3d \
jni/SDL/src/render \
jni/SDL/src/power/windows \
jni/SDL/src/power/nds \
jni/SDL/src/power/macosx \
jni/SDL/src/power/linux \
jni/SDL/src/power/beos \
jni/SDL/src/power \
jni/SDL/src/main/windows \
jni/SDL/src/main/dummy \
jni/SDL/src/main/android \
jni/SDL/src/loadso/windows \
jni/SDL/src/loadso/macosx \
jni/SDL/src/loadso/dummy \
jni/SDL/src/loadso/dlopen \
jni/SDL/src/loadso/beos \
jni/SDL/src/libm \
jni/SDL/src/joystick/windows \
jni/SDL/src/joystick/nds \
jni/SDL/src/joystick/linux \
jni/SDL/src/joystick/dummy \
jni/SDL/src/joystick/darwin \
jni/SDL/src/joystick/bsd \
jni/SDL/src/joystick/android \
jni/SDL/src/joystick \
jni/SDL/src/haptic/windows \
jni/SDL/src/haptic/nds \
jni/SDL/src/haptic/linux \
jni/SDL/src/haptic/dummy \
jni/SDL/src/haptic/darwin \
jni/SDL/src/haptic \
jni/SDL/src/file \
jni/SDL/src/events/nds \
jni/SDL/src/events \
jni/SDL/src/cpuinfo \
jni/SDL/src/core/windows \
jni/SDL/src/core/android \
jni/SDL/src/audio/windx5 \
jni/SDL/src/audio/windib \
jni/SDL/src/audio/ums \
jni/SDL/src/audio/sun \
jni/SDL/src/audio/qsa \
jni/SDL/src/audio/pulseaudio \
jni/SDL/src/audio/paudio \
jni/SDL/src/audio/nds \
jni/SDL/src/audio/nas \
jni/SDL/src/audio/macosx \
jni/SDL/src/audio/iphoneos \
jni/SDL/src/audio/fusionsound \
jni/SDL/src/audio/esd \
jni/SDL/src/audio/dummy \
jni/SDL/src/audio/dsp \
jni/SDL/src/audio/dma \
jni/SDL/src/audio/disk \
jni/SDL/src/audio/bsd \
jni/SDL/src/audio/arts \
jni/SDL/src/audio/android \
jni/SDL/src/audio/alsa \
jni/SDL/src/audio \
jni/SDL/src/atomic \
jni/SDL/src \

